// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-api-clients-go/importapi"
	"github.com/ONSdigital/dp-import-tracker/api"
	"sync"
)

var (
	lockImportAPIClientMockGetImportJob         sync.RWMutex
	lockImportAPIClientMockUpdateImportJobState sync.RWMutex
)

// Ensure, that ImportAPIClientMock does implement api.ImportAPIClient.
// If this is not the case, regenerate this file with moq.
var _ api.ImportAPIClient = &ImportAPIClientMock{}

// ImportAPIClientMock is a mock implementation of api.ImportAPIClient.
//
//     func TestSomethingThatUsesImportAPIClient(t *testing.T) {
//
//         // make and configure a mocked api.ImportAPIClient
//         mockedImportAPIClient := &ImportAPIClientMock{
//             GetImportJobFunc: func(ctx context.Context, importJobID string, serviceToken string) (importapi.ImportJob, error) {
// 	               panic("mock out the GetImportJob method")
//             },
//             UpdateImportJobStateFunc: func(ctx context.Context, jobID string, serviceToken string, newState string) error {
// 	               panic("mock out the UpdateImportJobState method")
//             },
//         }
//
//         // use mockedImportAPIClient in code that requires api.ImportAPIClient
//         // and then make assertions.
//
//     }
type ImportAPIClientMock struct {
	// GetImportJobFunc mocks the GetImportJob method.
	GetImportJobFunc func(ctx context.Context, importJobID string, serviceToken string) (importapi.ImportJob, error)

	// UpdateImportJobStateFunc mocks the UpdateImportJobState method.
	UpdateImportJobStateFunc func(ctx context.Context, jobID string, serviceToken string, newState string) error

	// calls tracks calls to the methods.
	calls struct {
		// GetImportJob holds details about calls to the GetImportJob method.
		GetImportJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ImportJobID is the importJobID argument value.
			ImportJobID string
			// ServiceToken is the serviceToken argument value.
			ServiceToken string
		}
		// UpdateImportJobState holds details about calls to the UpdateImportJobState method.
		UpdateImportJobState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
			// ServiceToken is the serviceToken argument value.
			ServiceToken string
			// NewState is the newState argument value.
			NewState string
		}
	}
}

// GetImportJob calls GetImportJobFunc.
func (mock *ImportAPIClientMock) GetImportJob(ctx context.Context, importJobID string, serviceToken string) (importapi.ImportJob, error) {
	if mock.GetImportJobFunc == nil {
		panic("ImportAPIClientMock.GetImportJobFunc: method is nil but ImportAPIClient.GetImportJob was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ImportJobID  string
		ServiceToken string
	}{
		Ctx:          ctx,
		ImportJobID:  importJobID,
		ServiceToken: serviceToken,
	}
	lockImportAPIClientMockGetImportJob.Lock()
	mock.calls.GetImportJob = append(mock.calls.GetImportJob, callInfo)
	lockImportAPIClientMockGetImportJob.Unlock()
	return mock.GetImportJobFunc(ctx, importJobID, serviceToken)
}

// GetImportJobCalls gets all the calls that were made to GetImportJob.
// Check the length with:
//     len(mockedImportAPIClient.GetImportJobCalls())
func (mock *ImportAPIClientMock) GetImportJobCalls() []struct {
	Ctx          context.Context
	ImportJobID  string
	ServiceToken string
} {
	var calls []struct {
		Ctx          context.Context
		ImportJobID  string
		ServiceToken string
	}
	lockImportAPIClientMockGetImportJob.RLock()
	calls = mock.calls.GetImportJob
	lockImportAPIClientMockGetImportJob.RUnlock()
	return calls
}

// UpdateImportJobState calls UpdateImportJobStateFunc.
func (mock *ImportAPIClientMock) UpdateImportJobState(ctx context.Context, jobID string, serviceToken string, newState string) error {
	if mock.UpdateImportJobStateFunc == nil {
		panic("ImportAPIClientMock.UpdateImportJobStateFunc: method is nil but ImportAPIClient.UpdateImportJobState was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		JobID        string
		ServiceToken string
		NewState     string
	}{
		Ctx:          ctx,
		JobID:        jobID,
		ServiceToken: serviceToken,
		NewState:     newState,
	}
	lockImportAPIClientMockUpdateImportJobState.Lock()
	mock.calls.UpdateImportJobState = append(mock.calls.UpdateImportJobState, callInfo)
	lockImportAPIClientMockUpdateImportJobState.Unlock()
	return mock.UpdateImportJobStateFunc(ctx, jobID, serviceToken, newState)
}

// UpdateImportJobStateCalls gets all the calls that were made to UpdateImportJobState.
// Check the length with:
//     len(mockedImportAPIClient.UpdateImportJobStateCalls())
func (mock *ImportAPIClientMock) UpdateImportJobStateCalls() []struct {
	Ctx          context.Context
	JobID        string
	ServiceToken string
	NewState     string
} {
	var calls []struct {
		Ctx          context.Context
		JobID        string
		ServiceToken string
		NewState     string
	}
	lockImportAPIClientMockUpdateImportJobState.RLock()
	calls = mock.calls.UpdateImportJobState
	lockImportAPIClientMockUpdateImportJobState.RUnlock()
	return calls
}
