---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.12.5

inputs:
  - name: dp-import-tracker
    path: go/src/github.com/ONSdigital/dp-import-tracker

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-import-tracker/ci/scripts/build.sh
