---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.2

inputs:
  - name: dp-import-tracker
    path: dp-import-tracker

outputs:
  - name: build

run:
  path: dp-import-tracker/ci/scripts/build.sh
